
on:
  push:
    branches:
    - main
jobs:
      my_job:
        name: deploy to staging
        runs-on: ubuntu-latest
        
        steps:

        - name: Update diagram
          id: make_diagram
          uses: githubocto/repo-visualizer@0.7.1
          with:
            output_file: "output-diagram.svg"
            artifact_name: "diagram"
     
        - uses: actions/download-artifact@v4
          with:
            name: my-artifact
            path: your/destination/dir
        - name: Display structure of downloaded files
          run: ls -R your/destination/dir
          
              #should_push: false!
        - name: npm install, build and test
          run: |
            npm install
            npm run build --if-present
            npm test
   
          
